- name: Check login policy
# we need the pipe + newline to ensure Ansible
# doesn't treat the : as dictionary markup
  shell: |
    realm list | grep "^\s*login-policy: allow-permitted-logins$"
  ignore_errors: yes
  changed_when: no
  no_log: True
  register: login_policy

- name: Deny all realm logins
  shell: realm deny --all
  when: login_policy.rc != 0

# per-user access control is antipattern
# so only groups are supported here
- name: Check currently allowed groups
  shell: |
    realm list | grep "^\s*permitted-groups:.*{{ item }}.*"
  ignore_errors: yes
  changed_when: no
  no_log: True
  register: current_logins

- name: "Allow login for {{ item }}"
  shell: realm permit --groups "{{ item }}"
  when: current_logins.rc != 0
