- name: Check semanage availability
  shell: which semanage
  ignore_errors: yes
  changed_when: no
  no_log: True
  register: semanage_bin

- include_tasks: fcontext.yml
  when: semanage_bin.rc == 0
