- name: Check if machine is AD joined
  shell: "realm list | grep 'configured: kerberos-member'"
  ignore_errors: yes
  changed_when: no
  no_log: True
  register: ad_status

- fail:
    msg: "Host is not joined to AD. Make sure you run ad.yml, then join to the domain with 'realm join'."
  when: ad_status.rc != 0
