---
# new releases:
# - https://sourceforge.net/projects/e1000/files/
# - https://www.aquantia.com/support/driver-download/
# - https://www.mellanox.com/page/products_dyn?product_family=27

default_ext: tar.gz
sf_mirror: netcologne

drivers:
  atlantic:
    version: 2.2.6
    dkms_version: 2.2.6
    url: https://github.com/noobient/noobuntu/files/3718200/atlantic-2.2.6.tar.gz
    checksum: 36ff7685d090ac9c19085e470121ae5448c4b7d947e6566b8efb59f21dc6b1e2
    file_ext: '{{ default_ext }}'
    ko_name: atlantic
    dkms_name: atlantic
  e1000e:
    version: 3.5.1
    dkms_version: 3.5.1
    url: 'https://{{ sf_mirror }}.dl.sourceforge.net/project/e1000/e1000e%20stable/3.5.1/e1000e-3.5.1.tar.gz'
    checksum: 1b8c391c8c7114dcb65f20ae424ff8f89692c8daa4fe2569beecf9b2a2c9ae34
    file_ext: '{{ default_ext }}'
    ko_name: e1000e
    dkms_name: e1000e
    make_dir: src
  i40e:
    version: 2.9.21
    dkms_version: 2.9.21
    url: 'https://{{ sf_mirror }}.dl.sourceforge.net/project/e1000/i40e%20stable/2.9.21/i40e-2.9.21.tar.gz'
    checksum: fc9f185e73cf2a621970f3491c0c960954f287583ea5930d214c8dac5810597d
    file_ext: '{{ default_ext }}'
    ko_name: i40e
    dkms_name: i40e
    make_dir: src
  igb:
    version: 5.3.5.36
    dkms_version: 5.3.5.36
    url: 'https://{{ sf_mirror }}.dl.sourceforge.net/project/e1000/igb%20stable/5.3.5.36/igb-5.3.5.36.tar.gz'
    checksum: 87f69e85235443ced50b9f87f01e574b7cc620089a02ba2223e0be438e50fda6
    file_ext: '{{ default_ext }}'
    ko_name: igb
    dkms_name: igb
    make_dir: src
  ixgbe:
    version: 5.6.1
    dkms_version: 5.6.1
    url: 'https://{{ sf_mirror }}.dl.sourceforge.net/project/e1000/ixgbe%20stable/5.6.1/ixgbe-5.6.1.tar.gz'
    checksum: 7e5d3fefe429dfdc989da4478e176ef95808d250cb616bd8400374c3831a7ee3
    file_ext: '{{ default_ext }}'
    ko_name: ixgbe
    dkms_name: ixgbe
    make_dir: src
  tn40xx:
    version: 0.3.6.17.1
    dkms_version: 0.3.6.17.1
    url: https://github.com/noobient/noobuntu/files/3718202/tn40xx-0.3.6.17.1.tar.gz
    checksum: 8a7910c64c11b7267b9d21bb4f04762e37daca2abf18ef4ff6caea7e189f789a
    file_ext: '{{ default_ext }}'
    ko_name: tn40xx
    dkms_name: tn40xx
    make_args: 'MV88X3310=YES AQ=YES'
