---
- include_tasks: azure.yml

- include_role:
    name: devenv
    tasks_from: 3rdparty
  with_items:
  - { name: 'Azure CLI', gpg_url: 'https://packages.microsoft.com/keys/microsoft.asc', repo_file: 'azure-cli', package: 'azure-cli' }
  - { name: 'ceph-deploy', gpg_url: 'https://download.ceph.com/keys/release.asc', repo_file: 'ceph', package: 'ceph-deploy' }
  loop_control:
    loop_var: item

- include_tasks: powershell.yml
- include_tasks: asdm.yml
  when: asa_host is defined
