- name: Install perf
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - linux-tools-common
    - "linux-generic-hwe-{{ ubuntu_version }}-edge"

# https://www.jetbrains.com/help/clion/cpu-profiler.html
- name: Apply profiling kernel options
  copy:
    src: 99-perf.conf
    dest: /etc/sysctl.d/99-perf.conf
  notify: Reload sysctl
