- name: Obtain CUDA runfile
  get_url:
    url: "{{ cuda_url }}"
    dest: /usr/local/src/cuda.run
    checksum: "sha256:{{ cuda_checksum }}"
    mode: 0755

- name: Check installed CUDA version
  shell: cat /usr/local/cuda/version.txt
  ignore_errors: yes
  changed_when: no
  no_log: True
  register: cuda_ver

# if DISPLAY is set, runfile fails coz no TTY
- name: Install CUDA
  shell: "/usr/local/src/cuda.run --silent --toolkit --samples"
  environment:
    DISPLAY: 
  when: cuda_ver.stdout.find(cuda_verstr) == -1
