- name: Add CUDA libs to library path
  lineinfile:
    path: "/etc/ld.so.conf.d/cuda-{{ cuda_package_version }}.conf"
    create: yes
    mode: 0644
    owner: root
    group: root
    line: "/usr/local/cuda-{{ cuda_path_version }}/targets/x86_64-linux/lib"
  notify: Run ldconfig
