---
- include_role:
    name: nvidia

- include_tasks: ld_old.yml

- include_tasks: cuda_runfile.yml
  when: cuda_runfile_install == True
- include_tasks: cuda_repo.yml
  when: cuda_runfile_install != True

- include_tasks: libs.yml
- include_tasks: ld_current.yml
