# https://www.nomachine.com/AR12P01007
- name: Enable PAM auth for NoMachine
  ini_file:
    path: /etc/sssd/sssd.conf
    section: domain/ad.adasworks.com
    option: ad_gpo_map_network
    value: +nx
  notify: Restart SSSD

# https://www.nomachine.com/es/AR09N00902
- include_role:
    name: sedtemplate
  loop:
  - { desc: 'NX common session', regex: 's@^session(\s*)optional(\s*)pam_mount.so\s*$@session\1optional\2pam_mount.so disable_noninteractive@', src: '/etc/pam.d/common-session', dest: '/etc/pam.d/common-session-nx'}
  - { desc: 'NX su', regex: 's/^@include(\s*)common-session\s*$/@include\1common-session-nx/', src: '/etc/pam.d/su', dest: '/etc/pam.d/su-nx'}

- name: Fix NX pam service file
  replace:
    path: /etc/pam.d/nx
    regexp: '^session(\s*)include(\s*)su$'
    replace: 'session\1include\2su-nx'
    backup: yes
