- name: Install Mellanox driver
  apt:
    name: "{{ item }}"
  loop:
    - mlnx-en-eth-only
    - mlnx-fw-updater

# we need this if a new NIC is installed and FW updater is already installed
- name: Update Mellanox firmware
  command: /opt/mellanox/mlnx-fw-updater/mlnx_fw_updater.pl
  register: mlnx_fw
  changed_when: '"Update required" in mlnx_fw.stdout'
  failed_when: (mlnx_fw.rc != 0) and ("No devices found!" not in mlnx_fw.stdout)

- name: Enable firmware auto-update
  copy:
    src: mlnx-fw
    dest: /etc/cron.d/mlnx-fw
