---
- include_tasks: install.yml
- include_tasks: hostname.yml
- include_tasks: sssd.yml
- include_tasks: kerberos.yml
- include_tasks: ntp.yml
- include_tasks: realmd.yml
- include_tasks: homedir.yml
- include_tasks: nss.yml
- include_tasks: gdm.yml
- include_tasks: resolved.yml
