- name: Sync NTP from DCs
  ini_file:
    path: /etc/systemd/timesyncd.conf
    section: Time
    option: NTP
    value: "{{ ad_ntp_dc }}.{{ ad_domain }}"
    no_extra_spaces: yes
  notify:
  - Restart time sync service
  - Force time sync
