- name: Ensure SSSD conf.d directory exists
  file:
    state: directory
    path: /etc/sssd/conf.d
    recurse: yes

- name: Set up SSSD options
  ini_file:
    path: /etc/sssd/conf.d/services.conf
    owner: root
    group: root
    mode: 0600
    section: sssd
    option: services
    value: nss, pam, sudo

# https://bugs.launchpad.net/ubuntu/+source/sssd/+bug/1723350/comments/49
# https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path
- include_role:
    name: sedtemplate
  loop:
  - { desc: 'SSSD systemd unit', regex: '/^Wants=.*/a After=systemd-resolved.service', src: '/lib/systemd/system/sssd.service', dest: '/etc/systemd/system/sssd.service'}
