# https://www.nomachine.com/AR12P01007
- include_tasks: confd.yml
  loop:
  - { file: 'nomachine', section: "domain/{{ ad_domain }}", option: 'ad_gpo_map_network', value: '+nx'}

# TODO remove this sometime and move the above to main.yml
- name: Remove old NoMachine setup remnants
  ini_file:
    path: /etc/sssd/sssd.conf
    section: "domain/{{ ad_domain }}"
    option: ad_gpo_map_network
    value: +nx
    state: absent
  notify: Restart SSSD
