#- name: Install appimaged dependencies
#  apt:
#    name: libglib2.0-dev
#    state: latest
#    install_recommends: no

#- name: Install appimaged for system integration
#  apt:
#    deb: https://github.com/AppImage/appimaged/releases/download/continuous/appimaged_1-alpha-git2e34378.travis108_amd64.deb

#- name: Deploy appimaged system service
#  copy:
#    src: appimaged.service
#    dest: /lib/systemd/system/appimaged.service

#- name: Reload systemd units
#  systemd:
#    daemon_reload: yes

#- name: Enable appimaged service
#  systemd:
#    name: appimaged
#    enabled: yes
#    state: started

- name: Create global AppImage folder
  file:
    path: /Applications
    state: directory
    owner: root
    group: domain users
    mode: 0775

- name: Check if AppImage folder is in PATH
  command: grep Applications /etc/environment
  ignore_errors: yes
  changed_when: no
  no_log: True
  register: appspath

- name: Add AppImage folder to PATH
  lineinfile:
    path: /etc/environment
    regexp: '(^PATH=".*)"$'
    line: '\1:/Applications"'
    backrefs: yes
  when: appspath.rc != 0

#- name: Download AppImageUpdate
#  get_url:
#    url: https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
#    dest: /Applications/AppImageUpdate
#    owner: root
#    group: domain users
#    mode: 0775
