- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: latest
    install_recommends: no

- name: Update package lists
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: ^APT::Periodic::Update-Package-Lists.*
    line: APT::Periodic::Update-Package-Lists "1";

- name: Download package updates
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: ^APT::Periodic::Download-Upgradeable-Packages.*;
    line: APT::Periodic::Download-Upgradeable-Packages "1";

- name: Enable automatic cleanup
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: ^APT::Periodic::AutocleanInterval.*
    line: APT::Periodic::AutocleanInterval "7";

- name: Enable unattended upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: ^APT::Periodic::Unattended-Upgrade.*
    line: APT::Periodic::Unattended-Upgrade "1";

- name: Remove unused kernel versions
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: ^Unattended-Upgrade::Remove-Unused-Kernel-Packages.*
    line: Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

- name: Remove unusued dependencies
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: ^Unattended-Upgrade::Remove-Unused-Dependencies.*
    line: Unattended-Upgrade::Remove-Unused-Dependencies "true";

# remove // leading comment symbols from the -updates line
- name: Enable updates for -updates channel
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: ^\/\/(\s*)(\"\${distro_id}:\${distro_codename}-updates\";)
    line: \1\2
    backrefs: yes
