#- name: Check if Hiri is installed
#  command: snap list | grep ^hiri
#  ignore_errors: yes
#  changed_when: no
#  no_log: True
#  register: hirisnap

#- name: Install Hiri
#  command: snap install hiri
#  when: hirisnap.rc != 0

# snap version doesn't work
#- name: Install Hiri snap
#  snap:
#    name: hiri

- name: Install Evolution
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - evolution
    - evolution-ews
