- name: Various quality-of-life GNOME adjustments
  ini_file:
    path: /usr/local/share/glib-2.0/schemas/20_corporate-settings.gschema.override
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
    create: yes
  notify: Compile GLib schema
  with_items:
    # default domain for browsing shares
    - { section: "org.gnome.system.smb", option: "workgroup", value: "'AD'" }
    # https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/561370
    - { section: "org.gnome.Terminal.Legacy.Profile", option: "use-theme-transparency", value: 'false' }
    # terminal accelerator key conflicting with MC
    - { section: "org.gnome.Terminal.Legacy.Settings", option: "menu-accelerator-enabled", value: 'false' }
    # screenshot keyboard shortcut identical to Windows
    - { section: "org.gnome.settings-daemon.plugins.media-keys", option: "area-screenshot-clip", value: "'<Shift><Super>s'" }
    # disable switch apps shortcut
    - { section: "org.gnome.desktop.wm.keybindings", option: "switch-applications", value: "[]" }
    # enable switch windows shortcut
    - { section: "org.gnome.desktop.wm.keybindings", option: "switch-windows", value: "['<Super>Tab','<Alt>Tab']" }
    # bump lock screen timeout to 10 minutes
    - { section: "org.gnome.desktop.session", option: "idle-delay", value: "600" }
    # use location entry instead of pathbar
    #- { section: "org.gnome.nautilus.preferences", option: "always-use-location-entry", value: 'true' }

# glib-compile-schemas accepts only one dir and skips overrides without schema definitions
# so we need to put them in the same dir, but use symlinks to keep our local changes separated
- name: Symlink schema override from local to system dir
  file:
    src: /usr/local/share/glib-2.0/schemas/20_corporate-settings.gschema.override
    dest: /usr/share/glib-2.0/schemas/20_corporate-settings.gschema.override
    state: link
  notify: Compile GLib schema

- name: Make grouped window preview order static
  patch:
    src: static-dock-preview-order.patch
    dest: /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/windowPreview.js
    backup: yes
