---
- include_role:
    name: varcheck
  with_items:
  - teams_version
  - gcm4ml_version
  - fscrypt_revision
  - github_version
  - ad_domain
  - ad_smb_shares
  loop_control:
    loop_var: item
  vars:
  - parent: devenv

- include_tasks: utils.yml
- include_tasks: tty.yml
#- include_tasks: adcheck.yml
- include_tasks: gnome.yml
- include_tasks: apparmor.yml
#- include_tasks: email.yml

- include_role:
    name: 3rdparty
  loop:
  - { name: 'Clevis', gpg_url: 'https://apt.noobient.com/files/noobuntu.asc', repo_file: 'noobuntu', package: 'clevis' }
  - { name: 'Google Chrome', gpg_file: 'google-chrome', repo_file: 'google-chrome', package: 'google-chrome-stable', repo_overwrite: True }
  - { name: 'Hiri', gpg_url: 'https://apt.noobient.com/files/noobuntu.asc', repo_file: 'noobuntu', package: 'hiri' }
  - { name: 'Node.js', gpg_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key', repo_file: 'nodesource', package: 'nodejs' }
  - { name: 'Spotify', gpg_url: 'https://download.spotify.com/debian/pubkey.gpg', repo_file: 'spotify', package: 'spotify-client' }
  - { name: 'pgAdmin', gpg_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc', repo_file: 'pgdg', package: 'pgadmin4' }
  - { name: 'Sublime Text', gpg_url: 'https://download.sublimetext.com/sublimehq-pub.gpg', repo_file: 'sublime-text', package: 'sublime-text' }
  - { name: 'Vagrant', gpg_server: 'keyserver.ubuntu.com', gpg_id: 'AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4', repo_file: 'wolfgang42-vagrant', package: 'vagrant' }
  - { name: 'VirtualBox', gpg_url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc', repo_file: 'virtualbox', package: 'virtualbox-6.0' }
  - { name: 'VS Code', gpg_url: 'https://packages.microsoft.com/keys/microsoft.asc', repo_file: 'vscode', package: 'code' }

- include_tasks: onedrive.yml

# these only work if AD joined
#- include_tasks: appimage.yml
#  when: ad_status.rc == 0
#- include_tasks: teams_appimage.yml
#  when: ad_status.rc == 0
#- include_tasks: teams_snap.yml
- include_tasks: teams_deb.yml

- include_tasks: ide.yml
- include_tasks: gcm4ml.yml
- include_tasks: putty.yml
# TODO evaluate if can be fixed without own scripts
#- include_tasks: apt.yml
- include_tasks: network.yml
- include_tasks: shares.yml
# TODO we settle with LUKS for now
#- include_tasks: fscrypt.yml
- include_tasks: firewall.yml

# keep this one as last
- include_tasks: cleanup.yml
