# Pageant is necessary as GNOME Keyring and thus Seahorse don't support Ed25519 yet
# Also, they don't seem to support dynamic loading, only permanent import to disk

- name: Install PuTTY
  apt:
    name: putty
    state: latest
    install_recommends: no

# this needs to be enabled per-user, must document it
- name: Deploy Pageant service
  copy:
    src: pageant.service
    dest: /usr/lib/systemd/user/pageant.service

# won't work with user units
#- name: Reload systemd units
#  systemd:
#    daemon_reload: yes
#    scope: user

# It seems impossible to override GNOME Keyring in a nice way, without disabling it completely for everyone
# https://www.scivision.dev/disable-gnome-keyring-ssh-agent/
# https://unix.stackexchange.com/questions/315004/where-does-gnome-keyring-set-ssh-auth-sock
# https://wiki.debian.org/Xsession

# .profile is overridden, must use .bashrc
- name: Source Pageant variables in Bash
  blockinfile:
    path: /etc/bash.bashrc
    block: |
      if [ -f "$HOME/.pageant" ]; then
        . "$HOME/.pageant"
      fi

# desktop apps don't rely on .bashrc
- name: Source Pageant variables in PuTTY
  replace:
    path: /usr/share/applications/putty.desktop
    regexp: '^Exec=putty(.*)'
    replace: 'Exec=sh -c "[ -f \$HOME/.pageant ] && . \$HOME/.pageant; putty\1"'

# desktop apps don't rely on .bashrc
- name: Source Pageant variables in GitHub Desktop
  replace:
    path: /usr/share/applications/github-desktop.desktop
    regexp: '^Exec="/opt/GitHub Desktop/github-desktop" (.*)'
    replace: 'Exec=sh -c "[ -f \$HOME/.pageant ] && . \$HOME/.pageant; /opt/GitHub\ Desktop/github-desktop \1"'

# desktop apps don't rely on .bashrc
- name: Source Pageant variables in Remmina
  replace:
    path: /usr/share/applications/org.remmina.Remmina.desktop
    regexp: '^Exec=/usr/bin/remmina(.*)'
    replace: 'Exec=sh -c "[ -f \$HOME/.pageant ] && . \$HOME/.pageant; /usr/bin/remmina\1"'

# desktop apps don't rely on .bashrc
- name: Source Pageant variables in FileZilla
  replace:
    path: /usr/share/applications/filezilla.desktop
    regexp: '^Exec=filezilla(.*)'
    replace: 'Exec=sh -c "[ -f \$HOME/.pageant ] && . \$HOME/.pageant; filezilla\1"'
