# TODO remove once newer version has this built-in
- name: Add HEIF plugin PPA
  apt_repository:
    repo: ppa:jakar/qt-heif

- name: Add Git PPA
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: yes

- name: Add GIMP PPA
  apt_repository:
    repo: ppa:otto-kesselgulasch/gimp
    update_cache: yes

- name: Install useful utils
  apt:
    name: "{{ packages }}"
    install_recommends: yes
    state: latest
  vars:
    packages:
    - mc
    - git
    - git-lfs
    - git-gui
    - gitg
    - remmina
    - realmd
    - filezilla
    - vlc
    - gnome-system-monitor
    - nomacs
    - qt-heif-image-plugin
    - htop
    - nfs-common
    - usb-creator-gtk
    - gnome-calculator
    - p7zip-full
    - p7zip-rar
    - gparted
    - doublecmd-gtk
    - doublecmd-plugins
    - libffmpegthumbnailer4v5
    - unrar
    - mplayer
    - rabbitvcs-core
    - ffmpeg
    - libreoffice
    - openssh-server
    - ubuntu-desktop
    - net-tools
    - snapd
    - python3-pip
    - virtualenv
    - colordiff
    - meld
    - zip
    - fuse-zip
    - qbittorrent
    - vim
    - gstreamer1.0-libav
    - libcanberra-gtk-module
    - silversearcher-ag
    - gimp
    - gnome-tweaks
    - putty-tools

- name: Install GitHub dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gconf-service
    - gconf-service-backend
    - gconf2
    - gconf2-common
    - libappindicator1
    - libcurl4
    - libgconf-2-4
    - libindicator7

- name: Install GitHub Desktop
  apt:
    deb: "https://github.com/shiftkey/desktop/releases/download/release-{{ github_version }}/GitHubDesktop-linux-{{ github_version }}.deb"
