# TODO remove once newer version has this built-in
- name: Add HEIF plugin PPA
  apt_repository:
    repo: ppa:jakar/qt-heif

- name: Add GIMP PPA
  apt_repository:
    repo: ppa:otto-kesselgulasch/gimp
    update_cache: yes

- name: Install useful utils (deb)
  apt:
    name: "{{ packages }}"
    install_recommends: yes
    state: latest
  vars:
    packages:
    - mc
    - remmina
    - realmd
    - filezilla
    - vlc
    - gnome-system-monitor
    - nomacs
    - qt-heif-image-plugin
    - htop
    - nfs-common
    - usb-creator-gtk
    - gnome-calculator
    - gparted
    - doublecmd-gtk
    - doublecmd-plugins
    - libffmpegthumbnailer4v5
    - mplayer
    - rabbitvcs-core
    - ffmpeg
    - libreoffice
    - openssh-server
    - ubuntu-desktop
    - net-tools
    - snapd
    - python3-pip
    - virtualenv
    - colordiff
    - meld
    - qbittorrent
    - vim
    - gstreamer1.0-libav
    - libcanberra-gtk-module
    - silversearcher-ag
    - gimp
    - gnome-tweaks
    - putty-tools
    - screen
# TODO remove once added to mainline kernel
    - exfat-fuse
    - exfat-utils

- name: Install useful utils (snap)
  snap:
    name: "{{ item }}"
  loop:
    - prospect-mail
