---
- include_tasks: repo_ppa.yml
  when: cuda_runfile_install == True
- include_tasks: repo_cuda.yml
  when: cuda_runfile_install != True

- include_tasks: driver.yml

- include_role:
    name: devenv
    tasks_from: 3rdparty
  with_items:
  - { name: 'NVIDIA Container Toolkit', gpg_url: 'https://nvidia.github.io/nvidia-docker/gpgkey', repo_file: 'nvidia-docker', package: 'nvidia-container-toolkit' }
  loop_control:
    loop_var: item
